---
output: 
  html_document:
    toc: true # Activa el índice
    toc_float: true # Muestra el índice flotante
    css: styles.css
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

<div class="header-section">
  <h1>Demostraciones Estadística III</h1>
  <p>Bautista Martina Baldi - bautista.martina.baldi\@mi.unc.edu.ar</p>
  <p>2024-10</p>
</div>


# Introducción

A continuación se enuncian las demostraciones más probables para el final de la materia Estadística III de la FCE-UNC.

## Índice

- [Demostración 1](#demostración-1)  <!-- Enlace a la sección -->
- [Demostración 2](#demostración-2) 

## Demostración 1 {#demostración-1} 

Sea \(X\) una variable definida sobre un espacio de probabilidad \((\Omega; F; P)\). Demostrar que la probabilidad inducida por \(X\) verifica el axioma de \(\sigma\)-aditividad.

En primera instancia se define el significado de probabilidad inducida por \(X\). La probabilidad inducida por \(X\) sobre un conjunto \(B\) es \(P_{X}(B) = P(X^{-1}(B))\), donde \(X^{-1}(B)\) es el conjunto de todos los elementos de \(\Omega\) que son mapeados en \(B\) (por \(X\) en \(B\)).

Consideremos una secuencia de conjuntos \(B_{1}, B_{2}, \ldots \in F\).

Se quiere demostrar que 

$$
P_{X}\left(\bigcup_{i=1}^{\infty} B_{i}\right) = \sum_{i=1}^{\infty} P_{X}(B_{i}).
$$

Utilizando la definición de probabilidad inducida por \(X\), se tiene que 

$$
P_{X}\left(\bigcup_{i=1}^{\infty} B_{i}\right) = P\left(X^{-1}\left(\bigcup_{i=1}^{\infty} B_{i}\right)\right).
$$

Como los conjuntos \(B_{i}\) son disjuntos, entonces los conjuntos \(X^{-1}(B_{i})\) también lo son, porque \(X\) es una función. Entonces: 

$$
X^{-1}\left(\bigcup_{i=1}^{\infty} B_{i}\right) = \bigcup_{i=1}^{\infty} X^{-1}(B_{i}).
$$

Luego, haciendo uso de la propiedad de \(\sigma\)-aditividad de la medida de probabilidad \(P\), se tiene que: 

$$
P\left(X^{-1}\left(\bigcup_{i=1}^{\infty} B_{i}\right)\right) = P\left(\bigcup_{i=1}^{\infty} X^{-1}(B_{i})\right) = \sum_{i=1}^{\infty} P(X^{-1}(B_{i})).
$$

Por lo tanto, la probabilidad inducida por \(X\) verifica el axioma de \(\sigma\)-aditividad.

## Demostración 2 {#demostración-2}

Demostrar que la preimagen de los hiperrectángulos pertenece a $F$.

En primera instancia, se definen los hiperrectángulos de dimensión k como el producto cartesiano finito de los intervalos de la forma $(-\infty, X_k]$:

\[
X^{-1}\left( (-\infty, X_1] \times (-\infty, X_2] \times \dots \times (-\infty, X_k] \right) \in F
\]

\[
\left[ X^{-1}\left( \times_{i=1}^{k} (-\infty, X_i] \right) \right] \in F \quad \forall (X_1, \dots, X_k)
\]

\[
\updownarrow
\]

\[
[X \in \times_{i=1}^{k} (-\infty, X_i]]
\]

\[
\updownarrow
\]

\[
[X_1 \leq x_1, X_2 \leq x_2, \dots, X_k \leq x_k] = \{\omega \in \Omega : X_1(\omega) \leq x_1, \dots, X_k(\omega) \leq x_k\}
\]

De esta manera se satisfacen k restricciones:

\[
= \bigcap_{i=1}^{k} \{\omega \in \Omega : X_i(\omega) \leq x_i\}
\]

\[
= \bigcap_{i=1}^{k} [X_i \leq x_i]
\]

De lo anterior se sabe que $[X_i \leq x_i] \in F$ porque cada $X_i$ es una variable aleatoria.

Entonces, es posible afirmar que:

\[
= \bigcap_{i=1}^{k} [X_i \leq x_i] \in F
\]

que es lo que se quería demostrar.

## Demostración 3 {#demostración-3}

Sea $\{A_{n}\}_{n \geq 1}$ una sucesión de eventos tal que: $A_1 \subset A_2 \subset \dots \subset A_n$ y $A = \bigcup_{n=1}^{\infty} A_{n}$. 

Demostrar que: $\lim_{n \to \infty} P(A_{n}) = P(A)$. (Es decir, demostrar la continuidad de la probabilidad en sucesiones monótonas expansivas).
